version: "3"
services:
  hadoop-master:
    build:
      context: ../docker/hadoop-tarball
    container_name: hadoop-master-node
    command: "--run-as-master-with-slaves hadoop-slave-node hadoop-slave-node-2"
    ports:
      - "8088:8088"
      - "8042:8042"
      - "50070:50070"
      - "9009:9009"
  hadoop-slave:
    build:
      context: ../docker/hadoop-tarball
    container_name: hadoop-slave-node
    command: "--run-as-slave-with-master hadoop-master-node"
  hadoop-slave-2:
    build:
      context: ../docker/hadoop-tarball
    container_name: hadoop-slave-node-2
    command: "--run-as-slave-with-master hadoop-master-node"